language: node_js
node_js: 10
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
notifications:
  email: false
  slack:
    secure: Pv83b+vs0rzvofqsXHqgaiaKWpeQ80y09gbQhImTFZQ1Y5zOjz3vWmU3geCGK5WTzm8DnrLBMER67rct6GM4fZ8vobDPCz60LkoLKhlnOdgh/J8AQ5mChrXkRCsVLO7D9zVp7ae+GDJw4SnRcxhI9lGsa6lw9Y7cIqV7hTJQYiRE1srapCCVQBj1LFib0rL+qqGMvYkISrRSu1zzot+M8qOKxG2mB707x6vnVpWbbW6ZFL86RDNbHBhGE4uIl/LUtIifbalWSMbLY9UlyQkQPerXMLmB5FWJzy7+VAVDxSJkUYmUaRpNf7EAMLhU1WOcTUWKQR+OvN6VGiI/VAfxfI9dkaTGIBaBAtwyoDy4C6oVNtRQxfUXxqxfKN90kCqMf2vH3zn0kOxTmCXHKeHfgE7Oo+sX9LVQwbtFTfp1lsZ4VaSn/0QSiMrEYmD+uQnI7L/q0gaD88pgWKoo4co4dLQtSso4r11iOwjNcfETV0sz1ogKtKmu6vQTw5TbTNt0hLi2yqTo84mWRxtL4b04FzdoSwfs2A7D49qv/8PvfppBkeXzZTgacfxZe8ikjmyOlllAw57b9PuLf7V1HkAzzs7894qor+Ol/n6FOkbt3lMS4HeoYhGRGK3ooezG6V7g9pgGTmsuZu7Qr54cvMfLnccfs8On84mnzgi9Fx40fgg=
